name: CI

on:
  push:
    branches:
      - main
      - test

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 22.

      - name: Set env variables for main
        if: github.ref == 'refs/heads/main'
        run:  |
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> $GITHUB_ENV
      
      - name: Run npm install, build and test
        run:  |
          npm install
          npm run build
          npm run test

